---
- name: Deploy drone ci server
  hosts: drone
  become_user: root
  become: true
  vars_files:
    - "vars/main.yml"
  roles:
    - role: drone-ci
      # Version of Drone CI, see other versions here: https://hub.docker.com/r/drone/drone/tags/
      drone_version: 0.7

      # the url, where drone instance will be publicly available
      # typically you would have nginx in front of Drone CI
      drone_host: http://{{drone_server_ip}}

      # Version of PostgresSQL
      drone_postgress_version: 9.6.1

      # Variables below are configuraed using vars/credentials.yml & vars/main.yml
      drone_secret:
      drone_postgress_db:
      drone_postgress_user:
      drone_postgress_password:
      drone_github_client:
      drone_github_secret:
