- name: run drone server
  docker_container:
    name: drone-server
    image: "drone/drone:{{drone_version}}"
    state: started
    restart_policy: always
    ports:
      - "80:8000"
    volumes:
      - /var/lib/drone:/var/lib/drone/
    links:
      - postgres
    env:
      DRONE_HOST: "{{drone_host}}"
      DRONE_OPEN: "true"
      DRONE_GITHUB: "true"
      DRONE_GITHUB_CLIENT: "{{drone_github_client}}"
      DRONE_GITHUB_SECRET: "{{drone_github_secret}}"
      DRONE_SECRET: "{{drone_secret}}"
  tags:
    - drone
    - server

- name: run drone agent
  docker_container:
    name: "agent-{{item.name}}"
    image: "drone/agent:{{drone_version}}"
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone-server
    env:
      DRONE_SERVER: "ws://drone-server:8000/ws/broker"
      DRONE_SECRET: "{{drone_secret}}"
  with_items: "{{drone_agents}}"
  tags:
    - drone
    - agent
